doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            ip:  App\Infrastructure\Persistence\Doctrine\Type\IPDoctrineType
            email:  App\Infrastructure\Persistence\Doctrine\Type\EmailDoctrineType
            quantity:  App\Infrastructure\Persistence\Doctrine\Type\QuantityDoctrineType
            money:  App\Infrastructure\Persistence\Doctrine\Type\MoneyDoctrineType
            stock:  App\Infrastructure\Persistence\Doctrine\Type\StockDoctrineType
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Domain'
                alias: App
